/*
  Generated by Make DParser Version 1.30.6a201e22e57e77c297d3c43fdb245125ed3b7d64
  Available at http://dparser.sf.net
*/

#line 7 "jj.g.d_parser.c"
#include "dparse.h"

D_Reduction d_reduction_0_gram = {1, 0, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_1_gram = {1, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_2_gram = {2, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_3_gram = {1, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_4_gram = {1, 3, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_5_gram = {2, 4, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_7_gram = {1, 4, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_10_gram = {3, 5, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_11_gram = {1, 6, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_12_gram = {0, 6, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_13_gram = {6, 7, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_14_gram = {1, 8, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_15_gram = {0, 8, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_16_gram = {2, 9, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_17_gram = {6, 10, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_18_gram = {3, 11, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_19_gram = {2, 12, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_20_gram = {2, 13, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_21_gram = {0, 13, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_22_gram = {2, 14, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_23_gram = {2, 15, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_24_gram = {2, 16, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_25_gram = {0, 16, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_26_gram = {2, 17, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_27_gram = {2, 18, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_28_gram = {2, 19, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_29_gram = {0, 19, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_30_gram = {2, 20, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_31_gram = {1, 21, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_33_gram = {2, 22, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_34_gram = {2, 23, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_35_gram = {0, 23, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_36_gram = {2, 24, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_37_gram = {1, 25, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_41_gram = {2, 26, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_42_gram = {2, 27, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_43_gram = {0, 27, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_44_gram = {2, 28, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_45_gram = {1, 29, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_47_gram = {2, 30, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_48_gram = {2, 31, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_49_gram = {0, 31, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_50_gram = {2, 32, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_51_gram = {1, 33, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_53_gram = {2, 34, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_54_gram = {1, 35, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_56_gram = {1, 36, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_57_gram = {0, 36, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_58_gram = {1, 37, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_60_gram = {3, 38, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_61_gram = {1, 39, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_64_gram = {3, 39, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_65_gram = {5, 40, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_66_gram = {2, 41, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_67_gram = {0, 41, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_68_gram = {2, 42, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_69_gram = {1, 43, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_72_gram = {1, 44, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_73_gram = {1, 45, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_74_gram = {1, 46, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_75_gram = {1, 47, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_76_gram = {1, 48, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_77_gram = {2, 49, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_78_gram = {0, 49, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_79_gram = {1, 50, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_81_gram = {3, 51, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_0_gram = {52, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_1_gram = {53, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_2_gram = {54, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_3_gram = {55, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_4_gram = {56, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_5_gram = {57, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_6_gram = {58, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_7_gram = {59, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_8_gram = {60, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_9_gram = {61, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_10_gram = {62, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_11_gram = {63, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_12_gram = {64, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_13_gram = {65, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_14_gram = {66, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_15_gram = {67, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_16_gram = {68, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_17_gram = {69, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_18_gram = {70, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_19_gram = {71, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_20_gram = {72, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_21_gram = {73, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_22_gram = {74, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_23_gram = {75, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_24_gram = {76, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_25_gram = {77, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_26_gram = {78, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_27_gram = {79, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_28_gram = {80, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_29_gram = {81, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_30_gram = {82, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_31_gram = {83, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_32_gram = {84, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_33_gram = {85, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_34_gram = {86, 0, 0, 0, -1, 0, NULL};
D_Shift d_shift_35_gram = {87, 0, 0, 0, -2, 0, NULL};
D_Shift d_shift_36_gram = {88, 0, 0, 0, -3, 0, NULL};
D_Shift d_shift_37_gram = {89, 0, 0, 0, -4, 0, NULL};
D_Shift d_shift_38_gram = {90, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_39_gram = {91, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_40_gram = {92, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_41_gram = {93, 0, 0, 0, 0, 0, NULL};

D_Shift * d_accepts_diff_0_0_gram[] = {0};
D_Shift * d_accepts_diff_0_1_gram[] = {&d_shift_37_gram,0};
D_Shift * d_accepts_diff_0_2_gram[] = {&d_shift_5_gram,0};
D_Shift ** d_accepts_diff_0_gram[] = {
d_accepts_diff_0_0_gram,
d_accepts_diff_0_1_gram,
d_accepts_diff_0_2_gram
};

unsigned char d_scanner_0_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_0_1_gram[SCANNER_BLOCK_SIZE] = {
0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 3, 
0, 3, 3, 3, 4, 3, 3, 3, 3, 5, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 6, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_0_2_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_1_gram[] = {&d_shift_0_gram,NULL};

unsigned char d_scanner_0_2_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_2_1_gram[SCANNER_BLOCK_SIZE] = {
0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 3, 
0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_2_gram[] = {&d_shift_37_gram,NULL};

unsigned char d_scanner_0_3_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_3_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_4_1_gram[SCANNER_BLOCK_SIZE] = {
0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 3, 
0, 3, 3, 3, 3, 3, 8, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_5_gram[] = {&d_shift_3_gram,NULL};

unsigned char d_scanner_0_6_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_7_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_7_1_gram[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_7_gram[] = {&d_shift_5_gram,NULL};

unsigned char d_scanner_0_8_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_9_gram[] = {&d_shift_9_gram,NULL};

D_Shift * d_accepts_diff_4_0_gram[] = {0};
D_Shift ** d_accepts_diff_4_gram[] = {
d_accepts_diff_4_0_gram
};

unsigned char d_scanner_4_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_4_1_gram[] = {&d_shift_6_gram,NULL};

D_Shift * d_accepts_diff_13_0_gram[] = {0};
D_Shift ** d_accepts_diff_13_gram[] = {
d_accepts_diff_13_0_gram
};

D_Shift * d_accepts_diff_15_0_gram[] = {0};
D_Shift ** d_accepts_diff_15_gram[] = {
d_accepts_diff_15_0_gram
};

unsigned char d_scanner_15_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 
};

D_Shift * d_shift_15_1_gram[] = {&d_shift_12_gram,NULL};

D_Shift * d_accepts_diff_17_0_gram[] = {0};
D_Shift ** d_accepts_diff_17_gram[] = {
d_accepts_diff_17_0_gram
};

unsigned char d_scanner_17_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_17_1_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_17_1_gram[] = {&d_shift_38_gram,NULL};

D_Shift * d_shift_17_2_gram[] = {&d_shift_39_gram,NULL};

D_Shift * d_accepts_diff_19_0_gram[] = {0};
D_Shift ** d_accepts_diff_19_gram[] = {
d_accepts_diff_19_0_gram
};

D_Shift * d_shift_19_1_gram[] = {&d_shift_4_gram,NULL};

D_Shift * d_accepts_diff_20_0_gram[] = {0};
D_Shift ** d_accepts_diff_20_gram[] = {
d_accepts_diff_20_0_gram
};

unsigned char d_scanner_20_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 3, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_20_1_gram[] = {&d_shift_22_gram,NULL};

D_Shift * d_shift_20_2_gram[] = {&d_shift_23_gram,NULL};

D_Shift * d_accepts_diff_21_0_gram[] = {0};
D_Shift ** d_accepts_diff_21_gram[] = {
d_accepts_diff_21_0_gram
};

unsigned char d_scanner_21_0_1_gram[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_21_1_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_accepts_diff_27_0_gram[] = {0};
D_Shift ** d_accepts_diff_27_gram[] = {
d_accepts_diff_27_0_gram
};

unsigned char d_scanner_27_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

unsigned char d_scanner_27_0_1_gram[SCANNER_BLOCK_SIZE] = {
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

D_Shift * d_shift_27_0_gram[] = {&d_shift_40_gram,NULL};

D_Shift * d_accepts_diff_33_0_gram[] = {0};
D_Shift ** d_accepts_diff_33_gram[] = {
d_accepts_diff_33_0_gram
};

unsigned char d_scanner_33_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_33_1_gram[] = {&d_shift_7_gram,NULL};

D_Shift * d_accepts_diff_40_0_gram[] = {0};
D_Shift * d_accepts_diff_40_1_gram[] = {&d_shift_34_gram,0};
D_Shift ** d_accepts_diff_40_gram[] = {
d_accepts_diff_40_0_gram,
d_accepts_diff_40_1_gram
};

unsigned char d_scanner_40_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 3, 0, 
4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_40_0_1_gram[SCANNER_BLOCK_SIZE] = {
0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 6, 
0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_40_2_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_40_3_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_40_3_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_40_3_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_40_3_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_40_3_gram[] = {&d_shift_34_gram,NULL};

unsigned char d_scanner_40_4_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_40_4_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_40_5_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_40_6_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_40_6_gram[] = {&d_shift_35_gram,NULL};

unsigned char d_scanner_40_7_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_40_9_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 0, 13, 0, 0, 
14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_40_10_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, 15, 0, 0, 
16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_40_12_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_40_13_gram[] = {&d_shift_36_gram,NULL};

unsigned char d_scanner_40_14_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_accepts_diff_44_0_gram[] = {0};
D_Shift ** d_accepts_diff_44_gram[] = {
d_accepts_diff_44_0_gram
};

unsigned char d_scanner_44_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_44_1_gram[] = {&d_shift_41_gram,NULL};

D_Shift * d_accepts_diff_46_0_gram[] = {0};
D_Shift ** d_accepts_diff_46_gram[] = {
d_accepts_diff_46_0_gram
};

unsigned char d_scanner_46_0_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 
};

unsigned char d_scanner_46_1_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 
};

D_Shift * d_shift_46_2_gram[] = {&d_shift_14_gram,NULL};

D_Shift * d_accepts_diff_47_0_gram[] = {0};
D_Shift ** d_accepts_diff_47_gram[] = {
d_accepts_diff_47_0_gram
};

unsigned char d_scanner_47_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_47_1_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_47_2_gram[] = {&d_shift_15_gram,NULL};

D_Shift * d_accepts_diff_48_0_gram[] = {0};
D_Shift ** d_accepts_diff_48_gram[] = {
d_accepts_diff_48_0_gram
};

unsigned char d_scanner_48_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 
};

unsigned char d_scanner_48_1_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 
};

unsigned char d_scanner_48_2_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 
};

D_Shift * d_shift_48_3_gram[] = {&d_shift_16_gram,NULL};

D_Shift * d_shift_48_4_gram[] = {&d_shift_17_gram,NULL};

D_Shift * d_accepts_diff_49_0_gram[] = {0};
D_Shift * d_accepts_diff_49_1_gram[] = {&d_shift_18_gram,0};
D_Shift * d_accepts_diff_49_2_gram[] = {&d_shift_19_gram,0};
D_Shift ** d_accepts_diff_49_gram[] = {
d_accepts_diff_49_0_gram,
d_accepts_diff_49_1_gram,
d_accepts_diff_49_2_gram
};

unsigned char d_scanner_49_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 3, 0, 
};

unsigned char d_accepts_diff_49_1_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 
};

D_Shift * d_shift_49_1_gram[] = {&d_shift_18_gram,NULL};

unsigned char d_accepts_diff_49_2_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 
};

D_Shift * d_shift_49_2_gram[] = {&d_shift_19_gram,NULL};

D_Shift * d_shift_49_3_gram[] = {&d_shift_20_gram,NULL};

D_Shift * d_shift_49_4_gram[] = {&d_shift_21_gram,NULL};

D_Shift * d_accepts_diff_51_0_gram[] = {0};
D_Shift ** d_accepts_diff_51_gram[] = {
d_accepts_diff_51_0_gram
};

unsigned char d_scanner_51_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_51_1_gram[] = {&d_shift_24_gram,NULL};

D_Shift * d_shift_51_2_gram[] = {&d_shift_25_gram,NULL};

D_Shift * d_accepts_diff_58_0_gram[] = {0};
D_Shift ** d_accepts_diff_58_gram[] = {
d_accepts_diff_58_0_gram
};

unsigned char d_scanner_58_0_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_58_1_gram[] = {&d_shift_28_gram,NULL};

D_Shift * d_accepts_diff_67_0_gram[] = {0};
D_Shift ** d_accepts_diff_67_gram[] = {
d_accepts_diff_67_0_gram
};

unsigned char d_scanner_67_0_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_67_1_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_67_2_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_67_3_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_67_4_gram[] = {&d_shift_8_gram,NULL};

D_Shift * d_accepts_diff_108_0_gram[] = {0};
D_Shift ** d_accepts_diff_108_gram[] = {
d_accepts_diff_108_0_gram
};

unsigned char d_scanner_108_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 3, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_108_2_gram[] = {&d_shift_32_gram,NULL};

SB_uint8 d_scanner_0_gram[10] = {
{NULL, {d_scanner_0_0_0_gram, d_scanner_0_0_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_2_gram, {d_scanner_0_2_0_gram, d_scanner_0_2_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_2_gram, {d_scanner_0_3_0_gram, d_scanner_0_2_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_2_gram, {d_scanner_0_2_0_gram, d_scanner_0_4_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_5_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_0_0_2_gram, d_scanner_0_6_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_7_gram, {d_scanner_0_2_0_gram, d_scanner_0_2_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_0_0_2_gram, d_scanner_0_8_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_9_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_0_gram[10] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_3_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_7_0_gram, d_accepts_diff_0_7_1_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_4_gram[2] = {
{NULL, {d_scanner_4_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_4_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_4_gram[2] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_13_gram[2] = {
{NULL, {d_scanner_0_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_13_gram[2] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_15_gram[2] = {
{NULL, {d_scanner_15_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_15_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_15_gram[2] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_17_gram[3] = {
{NULL, {d_scanner_17_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_17_1_gram, {d_scanner_17_1_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_17_2_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_17_gram[3] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_19_gram[2] = {
{NULL, {d_scanner_0_0_2_gram, d_scanner_15_0_0_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_19_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_19_gram[2] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_20_gram[3] = {
{NULL, {d_scanner_20_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_20_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_20_2_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_20_gram[3] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_21_gram[2] = {
{NULL, {d_scanner_0_0_2_gram, d_scanner_21_0_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_2_gram, {d_scanner_21_1_0_gram, d_scanner_21_0_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_21_gram[2] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_27_gram[2] = {
{d_shift_27_0_gram, {d_scanner_27_0_0_gram, d_scanner_27_0_1_gram
 , d_scanner_27_0_1_gram, d_scanner_27_0_1_gram}},
{d_shift_27_0_gram, {d_scanner_27_0_0_gram, d_scanner_27_0_1_gram
 , d_scanner_27_0_1_gram, d_scanner_27_0_1_gram}}
};

SB_trans_uint8 d_transition_27_gram[2] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_33_gram[2] = {
{NULL, {d_scanner_33_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_33_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_33_gram[2] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_40_gram[16] = {
{NULL, {d_scanner_40_0_0_gram, d_scanner_40_0_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_4_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_40_2_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_40_3_gram, {d_scanner_40_3_0_gram, d_scanner_40_3_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_40_3_gram, {d_scanner_40_4_0_gram, d_scanner_40_3_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_2_gram, {d_scanner_40_5_0_gram, d_scanner_40_0_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_40_6_gram, {d_scanner_40_2_0_gram, d_scanner_40_6_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_40_6_gram, {d_scanner_40_7_0_gram, d_scanner_40_6_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_40_3_0_gram, d_scanner_40_3_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_40_9_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_40_10_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_40_6_gram, {d_scanner_40_7_0_gram, d_scanner_40_6_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_40_12_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_40_13_gram, {d_scanner_40_12_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_40_14_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_40_6_gram, {d_scanner_40_14_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_40_gram[16] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_40_3_0_gram, d_accepts_diff_40_3_1_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_40_4_0_gram, d_accepts_diff_40_3_1_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_44_gram[2] = {
{NULL, {d_scanner_44_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_44_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_44_gram[2] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_46_gram[3] = {
{NULL, {d_scanner_0_0_2_gram, d_scanner_46_0_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_0_0_2_gram, d_scanner_46_1_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_46_2_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_46_gram[3] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_47_gram[3] = {
{NULL, {d_scanner_47_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_47_1_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_47_2_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_47_gram[3] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_48_gram[5] = {
{NULL, {d_scanner_48_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_48_1_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_48_2_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_48_3_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_48_4_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_48_gram[5] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_49_gram[5] = {
{NULL, {d_scanner_49_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_49_1_gram, {d_scanner_48_1_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_49_2_gram, {d_scanner_48_2_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_49_3_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_49_4_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_49_gram[5] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_49_1_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_49_2_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_51_gram[3] = {
{NULL, {d_scanner_51_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_51_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_51_2_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_51_gram[3] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_58_gram[2] = {
{NULL, {d_scanner_0_0_2_gram, d_scanner_58_0_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_58_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_58_gram[2] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_67_gram[5] = {
{NULL, {d_scanner_0_0_2_gram, d_scanner_67_0_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_0_0_2_gram, d_scanner_67_1_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_0_0_2_gram, d_scanner_67_2_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_0_0_2_gram, d_scanner_67_3_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_67_4_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_67_gram[5] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_108_gram[3] = {
{NULL, {d_scanner_108_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_33_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_108_2_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_108_gram[3] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

unsigned char d_goto_valid_0_gram[] = {
0xbe,0xc,0x0,0x0,0x0,0x80,0x90,0x22,0x0,0x0,0x0,0x2};
unsigned char d_goto_valid_1_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x3,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_1_gram[] = {&d_reduction_78_gram};
D_RightEpsilonHint d_right_epsilon_hints_1_gram[] = {{0, 17, &d_reduction_76_gram}};
D_Reduction * d_reductions_2_gram[] = {&d_reduction_7_gram};
unsigned char d_goto_valid_3_gram[] = {
0xfe,0xc,0x0,0x0,0x0,0x80,0x90,0x22,0x0,0x0,0x0,0x2};
D_Reduction * d_reductions_3_gram[] = {&d_reduction_12_gram};
unsigned char d_goto_valid_4_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x4,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_5_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x4,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_6_gram[] = {&d_reduction_75_gram};
unsigned char d_goto_valid_8_gram[] = {
0xb8,0xc,0x0,0x0,0x0,0x80,0x90,0x22,0x0,0x0,0x0,0x2};
D_Reduction * d_reductions_8_gram[] = {&d_reduction_1_gram};
D_Reduction * d_reductions_9_gram[] = {&d_reduction_3_gram};
D_Reduction * d_reductions_10_gram[] = {&d_reduction_4_gram};
D_Reduction * d_reductions_11_gram[] = {&d_reduction_7_gram};
D_Reduction * d_reductions_12_gram[] = {&d_reduction_7_gram};
unsigned char d_goto_valid_13_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x10,0x0,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_14_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x10,0x0,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_15_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0};
unsigned char d_goto_valid_17_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0xc,0x0,0x0,0x0,0x0,0xc};
D_Reduction * d_reductions_17_gram[] = {&d_reduction_76_gram};
D_Reduction * d_reductions_18_gram[] = {&d_reduction_11_gram};
unsigned char d_goto_valid_19_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_20_gram[] = {
0x0,0x90,0x44,0x44,0x34,0x0,0x0,0x0,0x0,0xc,0x0,0x0};
D_Reduction * d_reductions_20_gram[] = {&d_reduction_57_gram};
unsigned char d_goto_valid_21_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x80,0x0,0x0,0x0,0x0,0x0,0x2};
D_Reduction * d_reductions_22_gram[] = {&d_reduction_2_gram};
D_Reduction * d_reductions_23_gram[] = {&d_reduction_5_gram};
D_Reduction * d_reductions_24_gram[] = {&d_reduction_5_gram};
unsigned char d_goto_valid_25_gram[] = {
0x0,0x0,0x0,0x44,0x34,0x0,0x0,0x0,0x0,0xc,0x0,0x0};
D_Reduction * d_reductions_25_gram[] = {&d_reduction_57_gram};
D_Reduction * d_reductions_26_gram[] = {&d_reduction_79_gram};
unsigned char d_goto_valid_27_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x10};
D_Reduction * d_reductions_28_gram[] = {&d_reduction_77_gram};
D_Reduction * d_reductions_29_gram[] = {&d_reduction_79_gram};
D_Reduction * d_reductions_30_gram[] = {&d_reduction_10_gram};
D_Reduction * d_reductions_31_gram[] = {&d_reduction_58_gram};
D_Reduction * d_reductions_32_gram[] = {&d_reduction_58_gram};
unsigned char d_goto_valid_33_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_34_gram[] = {
0x0,0x20,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_34_gram[] = {&d_reduction_21_gram};
D_RightEpsilonHint d_right_epsilon_hints_34_gram[] = {{0, 46, &d_reduction_19_gram}};
unsigned char d_goto_valid_35_gram[] = {
0x0,0x0,0x1,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_35_gram[] = {&d_reduction_25_gram};
D_RightEpsilonHint d_right_epsilon_hints_35_gram[] = {{0, 47, &d_reduction_23_gram}};
unsigned char d_goto_valid_36_gram[] = {
0x0,0x0,0x8,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_36_gram[] = {&d_reduction_29_gram};
D_RightEpsilonHint d_right_epsilon_hints_36_gram[] = {{0, 48, &d_reduction_27_gram}};
unsigned char d_goto_valid_37_gram[] = {
0x0,0x0,0x80,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_37_gram[] = {&d_reduction_35_gram};
D_RightEpsilonHint d_right_epsilon_hints_37_gram[] = {{0, 49, &d_reduction_33_gram}};
unsigned char d_goto_valid_38_gram[] = {
0x0,0x0,0x0,0x8,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_38_gram[] = {&d_reduction_43_gram};
D_RightEpsilonHint d_right_epsilon_hints_38_gram[] = {{0, 50, &d_reduction_41_gram}};
unsigned char d_goto_valid_39_gram[] = {
0x0,0x0,0x0,0x80,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_39_gram[] = {&d_reduction_49_gram};
D_RightEpsilonHint d_right_epsilon_hints_39_gram[] = {{0, 51, &d_reduction_47_gram}};
unsigned char d_goto_valid_40_gram[] = {
0x0,0x0,0x0,0x0,0xc8,0xf9,0x0,0x4,0x0,0x0,0xc0,0x3};
D_Reduction * d_reductions_41_gram[] = {&d_reduction_56_gram};
unsigned char d_goto_valid_42_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_43_gram[] = {&d_reduction_18_gram};
unsigned char d_goto_valid_44_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x20};
unsigned char d_goto_valid_45_gram[] = {
0xb0,0xc,0x0,0x0,0x0,0x80,0x90,0x22,0x0,0x0,0x0,0x2};
unsigned char d_goto_valid_46_gram[] = {
0x0,0x40,0x0,0x0,0x0,0x0,0x0,0x0,0x4,0x0,0x0,0x0};
D_Reduction * d_reductions_46_gram[] = {&d_reduction_19_gram};
unsigned char d_goto_valid_47_gram[] = {
0x0,0x0,0x2,0x0,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x0};
D_Reduction * d_reductions_47_gram[] = {&d_reduction_23_gram};
unsigned char d_goto_valid_48_gram[] = {
0x0,0x0,0x30,0x0,0x0,0x0,0x0,0x0,0x30,0x0,0x0,0x0};
D_Reduction * d_reductions_48_gram[] = {&d_reduction_27_gram};
unsigned char d_goto_valid_49_gram[] = {
0x0,0x0,0x0,0x3,0x0,0x0,0x0,0x0,0xc0,0x3,0x0,0x0};
D_Reduction * d_reductions_49_gram[] = {&d_reduction_33_gram};
unsigned char d_goto_valid_50_gram[] = {
0x0,0x0,0x0,0x30,0x0,0x0,0x0,0x0,0x0,0xc,0x0,0x0};
D_Reduction * d_reductions_50_gram[] = {&d_reduction_41_gram};
unsigned char d_goto_valid_51_gram[] = {
0x0,0x0,0x0,0x0,0x3,0x0,0x0,0x0,0x0,0x30,0x0,0x0};
D_Reduction * d_reductions_51_gram[] = {&d_reduction_47_gram};
unsigned char d_goto_valid_52_gram[] = {
0x0,0x0,0x0,0x44,0x34,0x0,0x0,0x0,0x0,0xc,0x0,0x0};
D_Reduction * d_reductions_52_gram[] = {&d_reduction_57_gram};
D_Reduction * d_reductions_53_gram[] = {&d_reduction_72_gram};
D_Reduction * d_reductions_54_gram[] = {&d_reduction_73_gram};
D_Reduction * d_reductions_55_gram[] = {&d_reduction_74_gram};
D_Reduction * d_reductions_56_gram[] = {&d_reduction_53_gram};
D_Reduction * d_reductions_57_gram[] = {&d_reduction_54_gram};
unsigned char d_goto_valid_58_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0};
D_Reduction * d_reductions_58_gram[] = {&d_reduction_54_gram};
D_Reduction * d_reductions_59_gram[] = {&d_reduction_61_gram};
D_Reduction * d_reductions_60_gram[] = {&d_reduction_61_gram};
D_Reduction * d_reductions_61_gram[] = {&d_reduction_69_gram};
D_Reduction * d_reductions_62_gram[] = {&d_reduction_69_gram};
D_Reduction * d_reductions_63_gram[] = {&d_reduction_69_gram};
unsigned char d_goto_valid_64_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x4,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_64_gram[] = {&d_reduction_61_gram};
unsigned char d_goto_valid_65_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0};
D_Reduction * d_reductions_66_gram[] = {&d_reduction_81_gram};
unsigned char d_goto_valid_67_gram[] = {
0x0,0x3,0x0,0x0,0x0,0x0,0x0,0x10,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_67_gram[] = {&d_reduction_15_gram};
D_RightEpsilonHint d_right_epsilon_hints_67_gram[] = {{0, 95, &d_reduction_13_gram}};
unsigned char d_goto_valid_68_gram[] = {
0x0,0x80,0x44,0x44,0x34,0x0,0x0,0x0,0x0,0xc,0x0,0x0};
D_Reduction * d_reductions_68_gram[] = {&d_reduction_57_gram};
D_Reduction * d_reductions_69_gram[] = {&d_reduction_20_gram};
unsigned char d_goto_valid_70_gram[] = {
0x0,0x0,0x44,0x44,0x34,0x0,0x0,0x0,0x0,0xc,0x0,0x0};
D_Reduction * d_reductions_70_gram[] = {&d_reduction_57_gram};
D_Reduction * d_reductions_71_gram[] = {&d_reduction_24_gram};
D_Reduction * d_reductions_72_gram[] = {&d_reduction_31_gram};
D_Reduction * d_reductions_73_gram[] = {&d_reduction_31_gram};
D_Reduction * d_reductions_74_gram[] = {&d_reduction_28_gram};
unsigned char d_goto_valid_75_gram[] = {
0x0,0x0,0x40,0x44,0x34,0x0,0x0,0x0,0x0,0xc,0x0,0x0};
D_Reduction * d_reductions_75_gram[] = {&d_reduction_57_gram};
D_Reduction * d_reductions_76_gram[] = {&d_reduction_37_gram};
D_Reduction * d_reductions_77_gram[] = {&d_reduction_37_gram};
D_Reduction * d_reductions_78_gram[] = {&d_reduction_37_gram};
D_Reduction * d_reductions_79_gram[] = {&d_reduction_37_gram};
D_Reduction * d_reductions_80_gram[] = {&d_reduction_34_gram};
unsigned char d_goto_valid_81_gram[] = {
0x0,0x0,0x0,0x44,0x34,0x0,0x0,0x0,0x0,0xc,0x0,0x0};
D_Reduction * d_reductions_81_gram[] = {&d_reduction_57_gram};
D_Reduction * d_reductions_82_gram[] = {&d_reduction_45_gram};
D_Reduction * d_reductions_83_gram[] = {&d_reduction_45_gram};
D_Reduction * d_reductions_84_gram[] = {&d_reduction_42_gram};
unsigned char d_goto_valid_85_gram[] = {
0x0,0x0,0x0,0x40,0x34,0x0,0x0,0x0,0x0,0xc,0x0,0x0};
D_Reduction * d_reductions_85_gram[] = {&d_reduction_57_gram};
D_Reduction * d_reductions_86_gram[] = {&d_reduction_51_gram};
D_Reduction * d_reductions_87_gram[] = {&d_reduction_51_gram};
D_Reduction * d_reductions_88_gram[] = {&d_reduction_48_gram};
unsigned char d_goto_valid_89_gram[] = {
0x0,0x0,0x0,0x0,0x34,0x0,0x0,0x0,0x0,0xc,0x0,0x0};
D_Reduction * d_reductions_89_gram[] = {&d_reduction_57_gram};
unsigned char d_goto_valid_90_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_91_gram[] = {
0x0,0x0,0x0,0x0,0x80,0xf9,0x0,0x4,0x0,0x0,0xc0,0x3};
unsigned char d_goto_valid_92_gram[] = {
0x0,0x0,0x0,0x44,0x34,0x0,0x0,0x0,0x0,0xc,0x0,0x0};
D_Reduction * d_reductions_92_gram[] = {&d_reduction_57_gram};
unsigned char d_goto_valid_93_gram[] = {
0x0,0x0,0x0,0x44,0x34,0x0,0x0,0x0,0x0,0xc,0x0,0x0};
D_Reduction * d_reductions_93_gram[] = {&d_reduction_57_gram};
unsigned char d_goto_valid_94_gram[] = {
0xb0,0xc,0x0,0x0,0x0,0x80,0x90,0x22,0x0,0x0,0x0,0x2};
D_Reduction * d_reductions_95_gram[] = {&d_reduction_13_gram};
D_Reduction * d_reductions_96_gram[] = {&d_reduction_14_gram};
D_Reduction * d_reductions_97_gram[] = {&d_reduction_22_gram};
D_Reduction * d_reductions_98_gram[] = {&d_reduction_26_gram};
D_Reduction * d_reductions_99_gram[] = {&d_reduction_30_gram};
D_Reduction * d_reductions_100_gram[] = {&d_reduction_36_gram};
D_Reduction * d_reductions_101_gram[] = {&d_reduction_44_gram};
D_Reduction * d_reductions_102_gram[] = {&d_reduction_50_gram};
D_Reduction * d_reductions_103_gram[] = {&d_reduction_64_gram};
D_Reduction * d_reductions_104_gram[] = {&d_reduction_60_gram};
unsigned char d_goto_valid_105_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_105_gram[] = {&d_reduction_67_gram};
D_Reduction * d_reductions_106_gram[] = {&d_reduction_17_gram};
D_Reduction * d_reductions_107_gram[] = {&d_reduction_16_gram};
unsigned char d_goto_valid_108_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x4,0x0,0x8,0x0,0x0,0x10,0x0};
D_Reduction * d_reductions_109_gram[] = {&d_reduction_65_gram};
unsigned char d_goto_valid_110_gram[] = {
0x0,0x0,0x0,0x44,0x34,0x0,0x0,0x0,0x0,0xc,0x0,0x0};
D_Reduction * d_reductions_110_gram[] = {&d_reduction_57_gram};
D_Reduction * d_reductions_111_gram[] = {&d_reduction_66_gram};
D_Reduction * d_reductions_112_gram[] = {&d_reduction_68_gram};
unsigned short d_gotos_gram[365] = {
8,9,10,11,12,21,13,17,18,14,15,19,9,10,11,12,
20,13,22,24,14,15,25,26,23,11,12,31,13,29,30,14,
15,43,45,46,47,48,49,50,51,52,66,67,70,72,16,92,
93,94,104,3,75,76,4,109,5,16,0,0,6,0,3,0,
0,4,0,5,16,27,28,6,0,3,0,7,4,0,5,0,
34,44,6,35,0,39,36,0,7,40,37,41,42,0,38,71,
69,0,39,7,73,74,40,57,41,42,58,59,60,0,7,61,
62,63,64,65,68,12,112,13,96,97,14,15,85,86,53,0,
0,32,33,81,82,0,0,110,91,89,90,0,39,0,32,33,
40,0,41,42,103,0,41,42,0,0,54,55,56,7,0,16,
111,0,0,0,3,0,0,4,0,5,83,84,95,6,0,0,
0,77,78,79,80,87,88,98,32,33,36,0,32,33,37,99,
0,0,38,37,0,0,39,38,0,7,40,39,41,42,0,40,
100,41,42,0,38,0,0,0,39,101,0,0,40,39,41,42,
0,40,102,41,42,0,40,0,41,42,0,0,0,0,0,0,
0,0,32,33,0,105,60,32,33,61,62,63,64,65,0,0,
108,12,0,13,32,33,14,15,53,32,33,0,106,0,32,33,
39,107,0,0,40,39,41,42,0,40,0,41,42,0,0,0,
0,0,0,0,54,55,56,7,0,0,0,16,0,0,0,0,
3,0,0,4,0,5,0,0,0,6,0,113,32,33,0,39,
0,32,33,40,0,41,42,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,32,33};

D_ErrorRecoveryHint d_error_recovery_hints_0_gram[] = {
{0, 4, ";"},
{0, 5, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_13_gram[] = {{1, 4, ";"}};
D_ErrorRecoveryHint d_error_recovery_hints_17_gram[] = {{0, 51, "\n"}};
D_ErrorRecoveryHint d_error_recovery_hints_19_gram[] = {{2, 5, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_23_gram[] = {{2, 4, ";"}};
D_ErrorRecoveryHint d_error_recovery_hints_27_gram[] = {{1, 51, "\n"}};
D_ErrorRecoveryHint d_error_recovery_hints_30_gram[] = {{3, 5, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_40_gram[] = {{0, 39, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_44_gram[] = {{2, 51, "\n"}};
D_ErrorRecoveryHint d_error_recovery_hints_52_gram[] = {{1, 39, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_64_gram[] = {{1, 40, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_66_gram[] = {{3, 51, "\n"}};
D_ErrorRecoveryHint d_error_recovery_hints_90_gram[] = {{2, 39, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_92_gram[] = {{2, 40, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_103_gram[] = {{3, 39, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_105_gram[] = {{3, 40, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_108_gram[] = {{4, 40, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_109_gram[] = {{5, 40, ")"}};

D_State d_states_gram[] = {
{d_goto_valid_0_gram, 1, {0, NULL}, {0, NULL}, {2, d_error_recovery_hints_0_gram}, 1, NULL, (void*)d_scanner_0_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_gram, d_accepts_diff_0_gram, -1},
{d_goto_valid_1_gram, 41, {1, d_reductions_1_gram}, {1, d_right_epsilon_hints_1_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_2_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_3_gram, -10, {1, d_reductions_3_gram}, {0, NULL}, {2, d_error_recovery_hints_0_gram}, 1, NULL, (void*)d_scanner_0_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_gram, d_accepts_diff_0_gram, -1},
{d_goto_valid_4_gram, 53, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_4_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_4_gram, d_accepts_diff_4_gram, -1},
{d_goto_valid_5_gram, 40, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_4_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_4_gram, d_accepts_diff_4_gram, -1},
{NULL, -2147483647, {1, d_reductions_6_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_8_gram, -21, {1, d_reductions_8_gram}, {0, NULL}, {2, d_error_recovery_hints_0_gram}, 1, NULL, (void*)d_scanner_0_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_gram, d_accepts_diff_0_gram, -1},
{NULL, -2147483647, {1, d_reductions_9_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_10_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_11_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_12_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_13_gram, 33, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_13_gram}, 1, NULL, (void*)d_scanner_13_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_13_gram, d_accepts_diff_13_gram, -1},
{d_goto_valid_14_gram, 30, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_13_gram}, 1, NULL, (void*)d_scanner_13_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_13_gram, d_accepts_diff_13_gram, -1},
{d_goto_valid_15_gram, 41, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_15_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_15_gram, d_accepts_diff_15_gram, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_17_gram, 21, {1, d_reductions_17_gram}, {0, NULL}, {1, d_error_recovery_hints_17_gram}, 1, NULL, (void*)d_scanner_17_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_17_gram, d_accepts_diff_17_gram, -1},
{NULL, -2147483647, {1, d_reductions_18_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_19_gram, 29, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_19_gram}, 1, NULL, (void*)d_scanner_19_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_19_gram, d_accepts_diff_19_gram, -1},
{d_goto_valid_20_gram, -68, {1, d_reductions_20_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_20_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_20_gram, d_accepts_diff_20_gram, -1},
{d_goto_valid_21_gram, 14, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_21_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_21_gram, d_accepts_diff_21_gram, -1},
{NULL, -2147483647, {1, d_reductions_22_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_23_gram}, {0, NULL}, {1, d_error_recovery_hints_23_gram}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_24_gram}, {0, NULL}, {1, d_error_recovery_hints_23_gram}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_25_gram, -55, {1, d_reductions_25_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_20_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_20_gram, d_accepts_diff_20_gram, -1},
{NULL, -2147483647, {1, d_reductions_26_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_27_gram, 58, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_27_gram}, 1, NULL, (void*)d_scanner_27_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_27_gram, d_accepts_diff_27_gram, -1},
{NULL, -2147483647, {1, d_reductions_28_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_29_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_30_gram}, {0, NULL}, {1, d_error_recovery_hints_30_gram}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_31_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_32_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_33_gram, 24, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_33_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_33_gram, d_accepts_diff_33_gram, -1},
{d_goto_valid_34_gram, -23, {1, d_reductions_34_gram}, {1, d_right_epsilon_hints_34_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_35_gram, -21, {1, d_reductions_35_gram}, {1, d_right_epsilon_hints_35_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_36_gram, -19, {1, d_reductions_36_gram}, {1, d_right_epsilon_hints_36_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_37_gram, -16, {1, d_reductions_37_gram}, {1, d_right_epsilon_hints_37_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_38_gram, -13, {1, d_reductions_38_gram}, {1, d_right_epsilon_hints_38_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_39_gram, -10, {1, d_reductions_39_gram}, {1, d_right_epsilon_hints_39_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_40_gram, -68, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_40_gram}, 1, NULL, (void*)d_scanner_40_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_40_gram, d_accepts_diff_40_gram, -1},
{NULL, -2147483647, {1, d_reductions_41_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_42_gram, 17, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_33_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_33_gram, d_accepts_diff_33_gram, -1},
{NULL, -2147483647, {1, d_reductions_43_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_44_gram, 50, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_44_gram}, 1, NULL, (void*)d_scanner_44_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_44_gram, d_accepts_diff_44_gram, -1},
{d_goto_valid_45_gram, -112, {0, NULL}, {0, NULL}, {2, d_error_recovery_hints_0_gram}, 1, NULL, (void*)d_scanner_0_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_gram, d_accepts_diff_0_gram, -1},
{d_goto_valid_46_gram, -30, {1, d_reductions_46_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_46_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_46_gram, d_accepts_diff_46_gram, -1},
{d_goto_valid_47_gram, -28, {1, d_reductions_47_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_47_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_47_gram, d_accepts_diff_47_gram, -1},
{d_goto_valid_48_gram, -32, {1, d_reductions_48_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_48_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_48_gram, d_accepts_diff_48_gram, -1},
{d_goto_valid_49_gram, -107, {1, d_reductions_49_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_49_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_49_gram, d_accepts_diff_49_gram, -1},
{d_goto_valid_50_gram, -96, {1, d_reductions_50_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_20_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_20_gram, d_accepts_diff_20_gram, -1},
{d_goto_valid_51_gram, -105, {1, d_reductions_51_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_51_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_51_gram, d_accepts_diff_51_gram, -1},
{d_goto_valid_52_gram, -110, {1, d_reductions_52_gram}, {0, NULL}, {1, d_error_recovery_hints_52_gram}, 1, NULL, (void*)d_scanner_20_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_20_gram, d_accepts_diff_20_gram, -1},
{NULL, -2147483647, {1, d_reductions_53_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_54_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_55_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_56_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_57_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_58_gram, 33, {1, d_reductions_58_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_58_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_58_gram, d_accepts_diff_58_gram, -1},
{NULL, -2147483647, {1, d_reductions_59_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_60_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_61_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_62_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_63_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_64_gram, 10, {1, d_reductions_64_gram}, {0, NULL}, {1, d_error_recovery_hints_64_gram}, 1, NULL, (void*)d_scanner_4_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_4_gram, d_accepts_diff_4_gram, -1},
{d_goto_valid_65_gram, 15, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_15_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_15_gram, d_accepts_diff_15_gram, -1},
{NULL, -2147483647, {1, d_reductions_66_gram}, {0, NULL}, {1, d_error_recovery_hints_66_gram}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_67_gram, -112, {1, d_reductions_67_gram}, {1, d_right_epsilon_hints_67_gram}, {0, NULL}, 1, NULL, (void*)d_scanner_67_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_67_gram, d_accepts_diff_67_gram, -1},
{d_goto_valid_68_gram, -168, {1, d_reductions_68_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_20_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_20_gram, d_accepts_diff_20_gram, -1},
{NULL, -2147483647, {1, d_reductions_69_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_70_gram, -173, {1, d_reductions_70_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_20_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_20_gram, d_accepts_diff_20_gram, -1},
{NULL, -2147483647, {1, d_reductions_71_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_72_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_73_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_74_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_75_gram, -186, {1, d_reductions_75_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_20_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_20_gram, d_accepts_diff_20_gram, -1},
{NULL, -2147483647, {1, d_reductions_76_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_77_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_78_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_79_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_80_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_81_gram, -191, {1, d_reductions_81_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_20_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_20_gram, d_accepts_diff_20_gram, -1},
{NULL, -2147483647, {1, d_reductions_82_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_83_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_84_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_85_gram, -196, {1, d_reductions_85_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_20_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_20_gram, d_accepts_diff_20_gram, -1},
{NULL, -2147483647, {1, d_reductions_86_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_87_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_88_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_89_gram, -114, {1, d_reductions_89_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_20_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_20_gram, d_accepts_diff_20_gram, -1},
{d_goto_valid_90_gram, 9, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_90_gram}, 1, NULL, (void*)d_scanner_33_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_33_gram, d_accepts_diff_33_gram, -1},
{d_goto_valid_91_gram, -206, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_40_gram}, 1, NULL, (void*)d_scanner_40_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_40_gram, d_accepts_diff_40_gram, -1},
{d_goto_valid_92_gram, -242, {1, d_reductions_92_gram}, {0, NULL}, {1, d_error_recovery_hints_92_gram}, 1, NULL, (void*)d_scanner_20_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_20_gram, d_accepts_diff_20_gram, -1},
{d_goto_valid_93_gram, -247, {1, d_reductions_93_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_20_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_20_gram, d_accepts_diff_20_gram, -1},
{d_goto_valid_94_gram, -252, {0, NULL}, {0, NULL}, {2, d_error_recovery_hints_0_gram}, 1, NULL, (void*)d_scanner_0_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_gram, d_accepts_diff_0_gram, -1},
{NULL, -2147483647, {1, d_reductions_95_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_96_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_97_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_98_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_99_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_100_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_101_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_102_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_103_gram}, {0, NULL}, {1, d_error_recovery_hints_103_gram}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_104_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_105_gram, -14, {1, d_reductions_105_gram}, {0, NULL}, {1, d_error_recovery_hints_105_gram}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_106_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_107_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_108_gram, -76, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_108_gram}, 1, NULL, (void*)d_scanner_108_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_108_gram, d_accepts_diff_108_gram, -1},
{NULL, -2147483647, {1, d_reductions_109_gram}, {0, NULL}, {1, d_error_recovery_hints_109_gram}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_110_gram, -289, {1, d_reductions_110_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_20_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_20_gram, d_accepts_diff_20_gram, -1},
{NULL, -2147483647, {1, d_reductions_111_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_112_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1}
};

D_Symbol d_symbols_gram[] = {
{D_SYMBOL_EBNF, "0 Start", 7, -1},
{D_SYMBOL_NTERM, "statement_list", 14, -1},
{D_SYMBOL_INTERNAL, "statement_list__3", 17, -1},
{D_SYMBOL_EBNF, "statement_list__2", 17, -1},
{D_SYMBOL_NTERM, "statement", 9, -1},
{D_SYMBOL_NTERM, "compound_statement", 18, -1},
{D_SYMBOL_INTERNAL, "compound_statement__6", 21, -1},
{D_SYMBOL_NTERM, "selection_statement", 19, -1},
{D_SYMBOL_INTERNAL, "selection_statement__9", 22, -1},
{D_SYMBOL_EBNF, "selection_statement__8", 22, -1},
{D_SYMBOL_NTERM, "derivative", 10, -1},
{D_SYMBOL_NTERM, "assignment", 10, -1},
{D_SYMBOL_NTERM, "logical_or_expression", 21, -1},
{D_SYMBOL_INTERNAL, "logical_or_expression__14", 25, -1},
{D_SYMBOL_EBNF, "logical_or_expression__13", 25, -1},
{D_SYMBOL_NTERM, "logical_and_expression", 22, -1},
{D_SYMBOL_INTERNAL, "logical_and_expression__17", 26, -1},
{D_SYMBOL_EBNF, "logical_and_expression__16", 26, -1},
{D_SYMBOL_NTERM, "equality_expression", 19, -1},
{D_SYMBOL_INTERNAL, "equality_expression__21", 23, -1},
{D_SYMBOL_EBNF, "equality_expression__19", 23, -1},
{D_SYMBOL_EBNF, "equality_expression__19__20", 27, -1},
{D_SYMBOL_NTERM, "relational_expression", 21, -1},
{D_SYMBOL_INTERNAL, "relational_expression__25", 25, -1},
{D_SYMBOL_EBNF, "relational_expression__23", 25, -1},
{D_SYMBOL_EBNF, "relational_expression__23__24", 29, -1},
{D_SYMBOL_NTERM, "additive_expression", 19, -1},
{D_SYMBOL_INTERNAL, "additive_expression__29", 23, -1},
{D_SYMBOL_EBNF, "additive_expression__27", 23, -1},
{D_SYMBOL_EBNF, "additive_expression__27__28", 27, -1},
{D_SYMBOL_NTERM, "multiplicative_expression", 25, -1},
{D_SYMBOL_INTERNAL, "multiplicative_expression__33", 29, -1},
{D_SYMBOL_EBNF, "multiplicative_expression__31", 29, -1},
{D_SYMBOL_EBNF, "multiplicative_expression__31__32", 33, -1},
{D_SYMBOL_NTERM, "unary_expression", 16, -1},
{D_SYMBOL_EBNF, "unary_expression__37", 20, -1},
{D_SYMBOL_INTERNAL, "unary_expression__36", 20, -1},
{D_SYMBOL_EBNF, "unary_expression__35", 20, -1},
{D_SYMBOL_NTERM, "power_expression", 16, -1},
{D_SYMBOL_NTERM, "primary_expression", 18, -1},
{D_SYMBOL_NTERM, "function", 8, -1},
{D_SYMBOL_INTERNAL, "function__42", 12, -1},
{D_SYMBOL_EBNF, "function__41", 12, -1},
{D_SYMBOL_NTERM, "constant", 8, -1},
{D_SYMBOL_NTERM, "decimalint", 10, -1},
{D_SYMBOL_NTERM, "float1", 6, -1},
{D_SYMBOL_NTERM, "float2", 6, -1},
{D_SYMBOL_NTERM, "identifier", 10, -1},
{D_SYMBOL_NTERM, "whitespace", 10, 1},
{D_SYMBOL_INTERNAL, "whitespace__50", 14, -1},
{D_SYMBOL_EBNF, "whitespace__49", 14, -1},
{D_SYMBOL_NTERM, "singleLineComment", 17, -1},
{D_SYMBOL_STRING, ";", 1},
{D_SYMBOL_STRING, ";", 1},
{D_SYMBOL_STRING, ";", 1},
{D_SYMBOL_STRING, "{", 1},
{D_SYMBOL_STRING, "}", 1},
{D_SYMBOL_STRING, "if", 2},
{D_SYMBOL_STRING, "(", 1},
{D_SYMBOL_STRING, ")", 1},
{D_SYMBOL_STRING, "else", 4},
{D_SYMBOL_STRING, "d/dt", 4},
{D_SYMBOL_STRING, "(", 1},
{D_SYMBOL_STRING, ")", 1},
{D_SYMBOL_STRING, "=", 1},
{D_SYMBOL_STRING, "=", 1},
{D_SYMBOL_STRING, "||", 2},
{D_SYMBOL_STRING, "&&", 2},
{D_SYMBOL_STRING, "!=", 2},
{D_SYMBOL_STRING, "==", 2},
{D_SYMBOL_STRING, "<", 1},
{D_SYMBOL_STRING, ">", 1},
{D_SYMBOL_STRING, "<=", 2},
{D_SYMBOL_STRING, ">=", 2},
{D_SYMBOL_STRING, "+", 1},
{D_SYMBOL_STRING, "-", 1},
{D_SYMBOL_STRING, "*", 1},
{D_SYMBOL_STRING, "/", 1},
{D_SYMBOL_STRING, "+", 1},
{D_SYMBOL_STRING, "-", 1},
{D_SYMBOL_STRING, "^", 1},
{D_SYMBOL_STRING, "(", 1},
{D_SYMBOL_STRING, ")", 1},
{D_SYMBOL_STRING, "(", 1},
{D_SYMBOL_STRING, ",", 1},
{D_SYMBOL_STRING, ")", 1},
{D_SYMBOL_REGEX, "0|([1-9][0-9]*)", 15},
{D_SYMBOL_REGEX, "([0-9]+.[0-9]*|[0-9]*.[0-9]+)([eE][\\\\-\\\\+]?[0-9]+)?", 55},
{D_SYMBOL_REGEX, "[0-9]+[eE][\\\\-\\\\+]?[0-9]+", 29},
{D_SYMBOL_REGEX, "[a-zA-Z_][a-zA-Z0-9_]*", 22},
{D_SYMBOL_REGEX, "[ \\t\\r\\n]+", 13},
{D_SYMBOL_STRING, "#", 1},
{D_SYMBOL_REGEX, "[^\\n]*", 7},
{D_SYMBOL_STRING, "\\n", 3},
};

D_ParserTables parser_tables_gram = {
113, d_states_gram, d_gotos_gram, 1, 94, d_symbols_gram, NULL, 0, NULL, 0};
