# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lin_cmt_stan <- function(obs_time, dose_time, dose, Tinf, params, oralSEXP, infusionSEXP, ncmtSEXP, parameterizationSEXP) {
    .Call(`_nlmixr_lin_cmt_stan`, obs_time, dose_time, dose, Tinf, params, oralSEXP, infusionSEXP, ncmtSEXP, parameterizationSEXP)
}

llik_binomial_c <- function(y, N, params) {
    .Call(`_nlmixr_llik_binomial_c`, y, N, params)
}

llik_poisson <- function(y, params) {
    .Call(`_nlmixr_llik_poisson`, y, params)
}

llik_normal <- function(y, params) {
    .Call(`_nlmixr_llik_normal`, y, params)
}

llik_betabinomial <- function(y, N, params) {
    .Call(`_nlmixr_llik_betabinomial`, y, N, params)
}

llik_student_t <- function(y, params) {
    .Call(`_nlmixr_llik_student_t`, y, params)
}

llik_beta <- function(y, params) {
    .Call(`_nlmixr_llik_beta`, y, params)
}

llik_neg_binomial <- function(y, params) {
    .Call(`_nlmixr_llik_neg_binomial`, y, params)
}

nlmixrParameters <- function(theta, eta) {
    .Call(`_nlmixr_nlmixrParameters`, theta, eta)
}

nlmixrShrink <- function(omegaMat, etasDf, etaLst) {
    .Call(`_nlmixr_nlmixrShrink`, omegaMat, etasDf, etaLst)
}

nlmixrResid <- function(innerList, omegaMat, dv, lambda, yj, etasDf, etaLst) {
    .Call(`_nlmixr_nlmixrResid`, innerList, omegaMat, dv, lambda, yj, etasDf, etaLst)
}

npde <- function(id, dv, sim, lambda, yj, ties = FALSE) {
    .Call(`_nlmixr_npde`, id, dv, sim, lambda, yj, ties)
}

