# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

freeFocei <- function() {
    invisible(.Call(`_nlmixr_freeFocei`))
}

foceiInnerLp <- function(eta, id = 1L) {
    .Call(`_nlmixr_foceiInnerLp`, eta, id)
}

likInner <- function(eta, id = 1L) {
    .Call(`_nlmixr_likInner`, eta, id)
}

cholSE_ <- function(A, tol) {
    .Call(`_nlmixr_cholSE_`, A, tol)
}

foceiLik <- function(theta) {
    .Call(`_nlmixr_foceiLik`, theta)
}

foceiOfv <- function(theta) {
    .Call(`_nlmixr_foceiOfv`, theta)
}

foceiEtas <- function() {
    .Call(`_nlmixr_foceiEtas`)
}

foceiNumericGrad <- function(theta) {
    .Call(`_nlmixr_foceiNumericGrad`, theta)
}

foceiSetup_ <- function(obj, data, theta, thetaFixed = NULL, skipCov = NULL, rxInv = NULL, lower = NULL, upper = NULL, etaMat = NULL, control = NULL) {
    .Call(`_nlmixr_foceiSetup_`, obj, data, theta, thetaFixed, skipCov, rxInv, lower, upper, etaMat, control)
}

foceiOuterF <- function(theta) {
    .Call(`_nlmixr_foceiOuterF`, theta)
}

foceiOuterG <- function(theta) {
    .Call(`_nlmixr_foceiOuterG`, theta)
}

foceiOuter <- function(e) {
    .Call(`_nlmixr_foceiOuter`, e)
}

nlmixrGill83_ <- function(what, args, envir, which, gillRtol, gillK = 10L, gillStep = 2, gillFtol = 0, optGillF = TRUE) {
    .Call(`_nlmixr_nlmixrGill83_`, what, args, envir, which, gillRtol, gillK, gillStep, gillFtol, optGillF)
}

#' @rdname nlmixrGradFun
#' @export
nlmixrEval_ <- function(theta, md5) {
    .Call(`_nlmixr_nlmixrEval_`, theta, md5)
}

#' @rdname nlmixrGradFun
#' @export
nlmixrUnscaled_ <- function(theta, md5) {
    .Call(`_nlmixr_nlmixrUnscaled_`, theta, md5)
}

#' @rdname nlmixrGradFun
#' @export
nlmixrGrad_ <- function(theta, md5) {
    .Call(`_nlmixr_nlmixrGrad_`, theta, md5)
}

#' @rdname nlmixrGradFun
#' @export
nlmixrParHist_ <- function(md5) {
    .Call(`_nlmixr_nlmixrParHist_`, md5)
}

nlmixrHess_ <- function(thetaT, fT, e, gillInfoT) {
    .Call(`_nlmixr_nlmixrHess_`, thetaT, fT, e, gillInfoT)
}

#' Return the square root of general square matrix A
#'
#' @param m Matrix to take the square root of.
#' @export
sqrtm <- function(m) {
    .Call(`_nlmixr_sqrtm`, m)
}

foceiCalcCov <- function(e) {
    .Call(`_nlmixr_foceiCalcCov`, e)
}

#' Fit/Evaulate FOCEi
#'
#' This shouldn't be called directly.
#'
#' @param e Enviornment
#'
#' @keywords internal
#' @export
foceiFitCpp_ <- function(e) {
    .Call(`_nlmixr_foceiFitCpp_`, e)
}

boxCox_ <- function(x = 1L, lambda = 1, yj = 0L) {
    .Call(`_nlmixr_boxCox_`, x, lambda, yj)
}

iBoxCox_ <- function(x = 1L, lambda = 1, yj = 0L) {
    .Call(`_nlmixr_iBoxCox_`, x, lambda, yj)
}

lin_cmt_stan <- function(obs_time, dose_time, dose, Tinf, params, oralSEXP, infusionSEXP, ncmtSEXP, parameterizationSEXP) {
    .Call(`_nlmixr_lin_cmt_stan`, obs_time, dose_time, dose, Tinf, params, oralSEXP, infusionSEXP, ncmtSEXP, parameterizationSEXP)
}

llik_binomial_c <- function(y, N, params) {
    .Call(`_nlmixr_llik_binomial_c`, y, N, params)
}

llik_poisson <- function(y, params) {
    .Call(`_nlmixr_llik_poisson`, y, params)
}

llik_normal <- function(y, params) {
    .Call(`_nlmixr_llik_normal`, y, params)
}

llik_betabinomial <- function(y, N, params) {
    .Call(`_nlmixr_llik_betabinomial`, y, N, params)
}

llik_student_t <- function(y, params) {
    .Call(`_nlmixr_llik_student_t`, y, params)
}

llik_beta <- function(y, params) {
    .Call(`_nlmixr_llik_beta`, y, params)
}

llik_neg_binomial <- function(y, params) {
    .Call(`_nlmixr_llik_neg_binomial`, y, params)
}

nlmixrParameters <- function(theta, eta) {
    .Call(`_nlmixr_nlmixrParameters`, theta, eta)
}

nlmixrShrink <- function(omegaMat, etasDf, etaLst) {
    .Call(`_nlmixr_nlmixrShrink`, omegaMat, etasDf, etaLst)
}

nlmixrResid <- function(innerList, omegaMat, cdv, evid, lambda, yj, cens, limit, etasDf, etaLst) {
    .Call(`_nlmixr_nlmixrResid`, innerList, omegaMat, cdv, evid, lambda, yj, cens, limit, etasDf, etaLst)
}

npde <- function(id, dv, evid, sim, lambda, yj, ties, tolChol) {
    .Call(`_nlmixr_npde`, id, dv, evid, sim, lambda, yj, ties, tolChol)
}

augPredTrans <- function(pred, ipred, lambda, yjIn) {
    .Call(`_nlmixr_augPredTrans`, pred, ipred, lambda, yjIn)
}

saemDoPred <- function(in_phi, in_evt, in_opt, cur, model, dll) {
    .Call(`_nlmixr_saemDoPred`, in_phi, in_evt, in_opt, cur, model, dll)
}

saemFit <- function(xSEXP, cur, model, dll) {
    .Call(`_nlmixr_saemFit`, xSEXP, cur, model, dll)
}

